development:
  adapter: postgresql
  encoding: unicode
  database: hangman_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: hangman_test
  pool: 5

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: hangman_production
#   pool: 5
