# Generated by cucumber-sinatra. (2014-03-14 16:36:09 -0400)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', './todo.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Todo

class TodoWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  TodoWorld.new
end
