development:
  adapter: postgresql
  encoding: unicode
  database: ttt_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: ttt_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: ttt_production
  pool: 5
