development:
  adapter: postgresql
  encoding: unicode
  database: Watchio_development
  pool: 5
  username: peterlai
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: Watchio_test
  pool: 5
  username: peterlai
  password:
