# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: movie_trailer_db
  encoding: unicode
  pool: 5
  timeout: 5000
  username: jessicasimon
  host: localhost



